# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maximsplashscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MaximSplashScreen(object):
    def setupUi(self, MaximSplashScreen):
        MaximSplashScreen.setObjectName("MaximSplashScreen")
        MaximSplashScreen.setWindowModality(QtCore.Qt.ApplicationModal)
        MaximSplashScreen.resize(400, 300)
        MaximSplashScreen.setMinimumSize(QtCore.QSize(400, 0))
        MaximSplashScreen.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        MaximSplashScreen.setFont(font)
        MaximSplashScreen.setAutoFillBackground(True)
        MaximSplashScreen.setStyleSheet("#centralWidget {\n"
"  background: rgba(32, 80, 96, 100);\n"
"  border-image: url(:/images/splash-screen-banner-no-txt.bmp);\n"
"}")
        self.pb_ok = QtWidgets.QPushButton(MaximSplashScreen)
        self.pb_ok.setGeometry(QtCore.QRect(260, 250, 90, 30))
        self.pb_ok.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_ok.setFont(font)
        self.pb_ok.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pb_ok.setObjectName("pb_ok")
        self.lbl_tool_name = QtWidgets.QLabel(MaximSplashScreen)
        self.lbl_tool_name.setGeometry(QtCore.QRect(30, 40, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_tool_name.setFont(font)
        self.lbl_tool_name.setAutoFillBackground(True)
        self.lbl_tool_name.setScaledContents(False)
        self.lbl_tool_name.setWordWrap(True)
        self.lbl_tool_name.setObjectName("lbl_tool_name")
        self.widget = QtWidgets.QWidget(MaximSplashScreen)
        self.widget.setGeometry(QtCore.QRect(30, 190, 311, 51))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_website = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_website.setFont(font)
        self.lbl_website.setObjectName("lbl_website")
        self.horizontalLayout.addWidget(self.lbl_website)
        self.lbl_website_text = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_website_text.setFont(font)
        self.lbl_website_text.setObjectName("lbl_website_text")
        self.horizontalLayout.addWidget(self.lbl_website_text)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_support = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_support.setFont(font)
        self.lbl_support.setObjectName("lbl_support")
        self.horizontalLayout_2.addWidget(self.lbl_support)
        self.lbl_support_text = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_support_text.setFont(font)
        self.lbl_support_text.setObjectName("lbl_support_text")
        self.horizontalLayout_2.addWidget(self.lbl_support_text)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.widget1 = QtWidgets.QWidget(MaximSplashScreen)
        self.widget1.setGeometry(QtCore.QRect(33, 103, 311, 54))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_version = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_version.sizePolicy().hasHeightForWidth())
        self.lbl_version.setSizePolicy(sizePolicy)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout.addWidget(self.lbl_version)
        self.lbl_trademark = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_trademark.sizePolicy().hasHeightForWidth())
        self.lbl_trademark.setSizePolicy(sizePolicy)
        self.lbl_trademark.setMinimumSize(QtCore.QSize(0, 30))
        self.lbl_trademark.setWordWrap(True)
        self.lbl_trademark.setObjectName("lbl_trademark")
        self.verticalLayout.addWidget(self.lbl_trademark)

        self.retranslateUi(MaximSplashScreen)
        QtCore.QMetaObject.connectSlotsByName(MaximSplashScreen)

    def retranslateUi(self, MaximSplashScreen):
        _translate = QtCore.QCoreApplication.translate
        MaximSplashScreen.setWindowTitle(_translate("MaximSplashScreen", "Dialog"))
        self.pb_ok.setText(_translate("MaximSplashScreen", "&OK"))
        self.lbl_tool_name.setText(_translate("MaximSplashScreen", "MAXIM Bootloader Tool"))
        self.lbl_website.setText(_translate("MaximSplashScreen", "Website:"))
        self.lbl_website_text.setText(_translate("MaximSplashScreen", "Text"))
        self.lbl_support.setText(_translate("MaximSplashScreen", "Support :"))
        self.lbl_support_text.setText(_translate("MaximSplashScreen", "Text"))
        self.lbl_version.setText(_translate("MaximSplashScreen", "Version"))
        self.lbl_trademark.setText(_translate("MaximSplashScreen", "TM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MaximSplashScreen = QtWidgets.QDialog()
    ui = Ui_MaximSplashScreen()
    ui.setupUi(MaximSplashScreen)
    MaximSplashScreen.show()
    sys.exit(app.exec_())
