from tkinter import Tk, LabelFrame

from src.common.look_and_feel import MXM_ICON, APP_TITLE, MXM_GREEN
from src.common.path_utils import convert_path_for_build
from src.generator.ble_renderer import execute_ble_renderer
from src.gui.mxm_widgets import MXMBrowseWidget, MXMButton, MXMEntry, MXMLabeledEntry, CreateToolTip


class App(Tk):
    def __init__(self):
        super().__init__()

        self.config(bg='#FFFFFF')

        try:
            self.iconbitmap(False, convert_path_for_build(MXM_ICON))
        except:
            print("No icon config")

        self.title(APP_TITLE)

        self.wrapper_frame = LabelFrame(self, background="#FFFFFF", relief="flat", highlightthickness=1,
                                        highlightbackground=MXM_GREEN, highlightcolor=MXM_GREEN)
        self.wrapper_frame.grid(row=1, column=1)

        self.wrapper_frame.grid_columnconfigure(2, minsize=10)  # Here

        # label
        self.excel_file_path = MXMBrowseWidget(self.wrapper_frame, browse_name="BLE Excel File Folder", browse_type=MXMBrowseWidget.FILE_BROWSE, tooltip="BLE service definition xlsx file")
        self.excel_file_path.grid(row=0, column=1, padx=5, pady=5, sticky="W")
        self.include_path_browse = MXMBrowseWidget(self.wrapper_frame, browse_name="Include Folder", tooltip="BLE autogenerated header files folder")
        self.include_path_browse.grid(row=1, column=1,padx=5, pady=5,sticky="W")
        self.source_path_browse = MXMBrowseWidget(self.wrapper_frame, browse_name="Source Folder", tooltip="BLE autogenerated source files folder")
        self.source_path_browse.grid(row=2, column=1,padx=5, pady=5,sticky="W")
        self.relative_header = MXMLabeledEntry(self.wrapper_frame, browse_name="Include File Relative Path",
                                               tooltip= "BLE source file relative path for include file this variable will be "
                                                        "included inside source file as  #include ${RELATIVE_PATH}/service_name.h");
        self.relative_header.grid(row=3, column=1,padx=5, pady=5,sticky="W")

        self.button_generate = MXMButton(self, text="Generate", command=self.generate)
        self.button_generate.grid(row=2, column=1, padx=13, pady=10)

    def generate(self):
        print("Generate Clicked")
        execute_ble_renderer(self.excel_file_path.get_selected_path(),
                             output_path_c=self.source_path_browse.get_selected_path(),
                             output_path_h=self.include_path_browse.get_selected_path(),
                             include_relative_path=self.relative_header.user_entry.get())
