/******************************************************************************
 * @file: sensio_services.c
 * @brief: This is the source fil provides functionality for BLE sensor data
 *         services to acquire sensor information, this source is autogenerated.
 *
 * Copyright (c) 2023 Sensio AI. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are not permitted
 *
 * Additional Reuse Declaration :
/*******************************************************************************
* Copyright (C) Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

/****************************************
* This file is autogenerated
* Do not edit this file
****************************************/

#include "sensio_service.h"
#include "svc_cfg.h"
#include <stdint.h>

/**************************************************************************************************
 SENSIO_SERVICE
**************************************************************************************************/

/**************************************************************************************************
 Defines
**************************************************************************************************/

/*! Characteristic read permissions */
#ifndef WP_SEC_PERMIT_READ
#define WP_SEC_PERMIT_READ SVC_SEC_PERMIT_READ
#endif

/*! Characteristic write permissions */
#ifndef WP_SEC_PERMIT_WRITE
#define WP_SEC_PERMIT_WRITE SVC_SEC_PERMIT_WRITE
#endif

#define UINT16_TO_BYTES(n)        ((uint8_t) (n)), ((uint8_t)((n) >> 8))
#define UUID_SIZE   6



/* Max Len Defines */
#define MAX_data_sensio_Read_Write_Len sizeof(ssensio_ServiceData.ssensio_ServiceData_NoGroup.data_sensio_Read_Write)
#define MAX_data_sensio_Read_Only_Len  sizeof(ssensio_ServiceData.ssensio_ServiceData_NoGroup.data_sensio_Read_Only)

/* UUID Defines */
#define ATT_UUID_SERVICE_SENSIO_SERVICE   0x57, 0xB3, 0x4A, 0x2A, 0x64, 0x8C, 0x69, 0x85, 0x92, 0xCF, 0x65, 0x26, 0x15, 0x1A, 0x77, 0x4E

#define ATT_UUID_sensio_Read_Write 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0xB7, 0x31, 0x24, 0x7C, 0x33, 0xB7, 0xB0, 0x7C, 0x83, 0x48
#define ATT_UUID_sensio_Read_Only  0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0xB7, 0x31, 0x24, 0x7C, 0x33, 0xB7, 0xB0, 0x7C, 0x83, 0x48
#define ATT_UUID_sensio_Write_Only 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0xB7, 0x31, 0x24, 0x7C, 0x33, 0xB7, 0xB0, 0x7C, 0x83, 0x48

/**************************************************************************************************
 Service UUID
**************************************************************************************************/
static const uint8_t svcDatUUID_sensio_Read_Write[] = {ATT_UUID_sensio_Read_Write};
static const uint8_t svcDatUUID_sensio_Read_Only[]  = {ATT_UUID_sensio_Read_Only};
static const uint8_t svcDatUUID_sensio_Write_Only[] = {ATT_UUID_sensio_Write_Only};

/**************************************************************************************************
 Proprietary data
**************************************************************************************************/

static tssensio_ServiceData ssensio_ServiceData =
{
    {
    },
};

/* Default Values
 */

/* Length data */
static uint16_t data_sensio_Read_Write_Len = MAX_data_sensio_Read_Write_Len;
static uint16_t data_sensio_Read_Only_Len = MAX_data_sensio_Read_Only_Len;
static uint16_t data_WpDatChCcc_Len = sizeof(ssensio_ServiceData.data_WpValDatChCcc);

/**************************************************************************************************
 Proprietary data characteristic
**************************************************************************************************/

static const uint8_t ch_Svc_sensio_Service[] = {ATT_UUID_SERVICE_SENSIO_SERVICE};
static const uint16_t ch_Svc_sensio_Service_Len = sizeof(ch_Svc_sensio_Service);

static const uint8_t ch_sensio_Read_Write[] = { ATT_PROP_NOTIFY | ATT_PROP_WRITE | ATT_PROP_WRITE_NO_RSP | ATT_PROP_READ, UINT16_TO_BYTES(HDL_DAT_sensio_Read_Write), ATT_UUID_sensio_Read_Write};
static const uint16_t ch_sensio_Read_Write_Len = sizeof(ch_sensio_Read_Write);

static const uint8_t ch_sensio_Read_Only[] = { ATT_PROP_READ, UINT16_TO_BYTES(HDL_DAT_sensio_Read_Only), ATT_UUID_sensio_Read_Only};
static const uint16_t ch_sensio_Read_Only_Len = sizeof(ch_sensio_Read_Only);


/**************************************************************************************************
 Attribute list for group
**************************************************************************************************/
static const attsAttr_t sensio_Service_WPList[] =
{

    {
        attPrimSvcUuid,
        (uint8_t *) &ch_Svc_sensio_Service[0],
        (uint16_t *) &ch_Svc_sensio_Service_Len,
        sizeof(ch_Svc_sensio_Service),
        0,
        ATTS_PERMIT_READ
    },
    /* UUID :: 48837CB0-B733-7C24-31B7-222222222222 */
    {
       attChUuid,
       (uint8_t *) ch_sensio_Read_Write,
       (uint16_t *) &ch_sensio_Read_Write_Len,
         sizeof(ch_sensio_Read_Write),
         0,
         ATTS_PERMIT_READ
    },
    {
         svcDatUUID_sensio_Read_Write,
         (uint8_t *) &ssensio_ServiceData.ssensio_ServiceData_NoGroup.data_sensio_Read_Write[0],
         (uint16_t *) &data_sensio_Read_Write_Len,
         MAX_data_sensio_Read_Write_Len,
         (ATTS_SET_UUID_128 | ATTS_SET_VARIABLE_LEN | ATTS_SET_WRITE_CBACK | ATTS_SET_READ_CBACK),
          WP_SEC_PERMIT_WRITE | WP_SEC_PERMIT_READ
    },
    /* UUID :: 48837CB0-B733-7C24-31B7-333333333333 */
    {
          attChUuid,
         (uint8_t *) ch_sensio_Read_Only,
         (uint16_t *) &ch_sensio_Read_Only_Len,
         sizeof(ch_sensio_Read_Only),
         0,
         ATTS_PERMIT_READ
    },
    {
         svcDatUUID_sensio_Read_Only,
         (uint8_t *) &ssensio_ServiceData.ssensio_ServiceData_NoGroup.data_sensio_Read_Only[0],
         (uint16_t *) &data_sensio_Read_Only_Len,
         MAX_data_sensio_Read_Only_Len,
         (ATTS_SET_UUID_128 | ATTS_SET_VARIABLE_LEN | ATTS_SET_READ_CBACK),
         (ATTS_PERMIT_READ | WP_SEC_PERMIT_READ)
    },
    {
        attCliChCfgUuid,
        (uint8_t *) ssensio_ServiceData.data_WpValDatChCcc,
        (uint16_t *) &data_WpDatChCcc_Len,
        sizeof(ssensio_ServiceData.data_WpValDatChCcc),
        ATTS_SET_CCC,
        (ATTS_PERMIT_READ | WP_SEC_PERMIT_WRITE)
    }
};

/* sensio_Service group structure */
static attsGroup_t svcGroupsensio_Service =
{
  NULL,
  (attsAttr_t *) sensio_Service_WPList,
  NULL,
  NULL,
  sensio_Service_START_HDL,
  sensio_Service_END_HDL
};

attsGroup_t* getGroupData_sensio_Service()
{
    return &svcGroupsensio_Service;
}

tssensio_ServiceData* getData_sensio_Service()
{
    return &ssensio_ServiceData;
}

void AddGroup_sensio_Service()
{
    AttsAddGroup(&svcGroupsensio_Service);
}

void registerCBack_sensio_Service(attsReadCback_t readCback, attsWriteCback_t writeCback)
{
    svcGroupsensio_Service.readCback = readCback;
    svcGroupsensio_Service.writeCback = writeCback;
}
