/******************************************************************************
 * @file: sensio_services.h
 * @brief: This is the source fil provides functionality for BLE sensor data
 *         services to acquire sensor information, this source is autogenerated.
 *
 * Copyright (c) 2023 Sensio AI. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are not permitted
 *
 * Additional Reuse Declaration :
 *******************************************************************************
 * Copyright (C) Maxim Integrated Products, Inc., All rights Reserved.
 *
 * This software is protected by copyright laws of the United States and
 * of foreign countries. This material may also be protected by patent laws
 * and technology transfer regulations of the United States and of foreign
 * countries. This software is furnished under a license agreement and/or a
 * nondisclosure agreement and may only be used or reproduced in accordance
 * with the terms of those agreements. Dissemination of this information to
 * any party or parties not specified in the license agreement and/or
 * nondisclosure agreement is expressly prohibited.
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
 * OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * Except as contained in this notice, the name of Maxim Integrated
 * Products, Inc. shall not be used except as stated in the Maxim Integrated
 * Products, Inc. Branding Policy.
 *
 * The mere transfer of this software does not imply any licenses
 * of trade secrets, proprietary technology, copyrights, patents,
 * trademarks, maskwork rights, or any other form of intellectual
 * property whatsoever. Maxim Integrated Products, Inc. retains all
 * ownership rights.
 *******************************************************************************/

/****************************************
* This file is autogenerated
* Do not edit this file
****************************************/

#ifndef SVC_SENSIO_SERVICE_H
#define SVC_SENSIO_SERVICE_H

#include "att_api.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 Defines
**************************************************************************************************/
#define sensio_Service_START_HDL               0x0800
#define sensio_Service_END_HDL                 (HDL_sensio_Service_MAX - 1)

/**************************************************************************************************
 Typedefs
**************************************************************************************************/

/**************************************************************************************************
 Handles
**************************************************************************************************/
enum
{
    HDL_SRV_sensio_Service = sensio_Service_START_HDL,
    HDL_CH_sensio_Read_Write ,
    HDL_DAT_sensio_Read_Write, /* Data Handler used for ECG */
    HDL_sensio_Service_CCC,
    HDL_CH_sensio_Read_Only ,
    HDL_DAT_sensio_Read_Only,  /* Data Handler Currently not used, can be used for RO values like Battery etc */
    HDL_sensio_Service_MAX,
};

/**************************************************************************************************
 Proprietary data
**************************************************************************************************/

/* Data */

typedef struct __attribute__((packed))
{
    uint8_t data_sensio_Read_Write[32];
    uint8_t data_sensio_Read_Only[32];
}tssensio_ServiceData_NoGroup;

typedef struct __attribute__((packed))
{
    tssensio_ServiceData_NoGroup ssensio_ServiceData_NoGroup;
    uint8_t data_WpValDatChCcc[1];
}tssensio_ServiceData;


/**************************************************************************************************
 Functions
**************************************************************************************************/
attsGroup_t* getGroupData_sensio_Service();
void registerCBack_sensio_Service(attsReadCback_t readCback, attsWriteCback_t writeCback);
tssensio_ServiceData* getData_sensio_Service();
void AddGroup_sensio_Service();


#ifdef __cplusplus
};
#endif

#endif /* SVC_SENSIO_SERVICE_H */
